"""Initial migration

Revision ID: dbc1421aad3c
Revises:
Create Date: 2024-09-12 18:38:08.536055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dbc1421aad3c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tender",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "Construction", "Delivery", "Manufacture", name="tenderservicetype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("Created", "Published", "Closed", name="tenderstatustype"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("creator_username", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="check_version_minimum"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "bid",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Created", "Published", "Canceled", name="bidstatustype"),
            nullable=False,
        ),
        sa.Column(
            "author_type",
            sa.Enum("Organization", "User", name="bidauthortype"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="check_version_minimum"),
        sa.ForeignKeyConstraint(["author_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tender.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "description", "author_type", "author_id", name="uq_tender_bid"
        ),
    )
    op.create_table(
        "tender_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "Construction", "Delivery", "Manufacture", name="tenderservicetype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("Created", "Published", "Closed", name="tenderstatustype"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("creator_username", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name="check_version_minimum"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tender_id"], ["tender.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bid_decision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bid_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("Approved", "Rejected", name="biddecisiontype"),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["bid_id"], ["bid.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bid_responsible",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bid_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["bid_id"], ["bid.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bid_review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("bid_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bid_id"], ["bid.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bid_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Created", "Published", "Canceled", name="bidstatustype"),
            nullable=False,
        ),
        sa.Column(
            "author_type",
            sa.Enum("Organization", "User", name="bidauthortype"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("bid_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name="check_version_minimum"),
        sa.ForeignKeyConstraint(["author_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["bid_id"], ["bid.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tender.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bid_version")
    op.drop_table("bid_review")
    op.drop_table("bid_responsible")
    op.drop_table("bid_decision")
    op.drop_table("tender_version")
    op.drop_table("bid")
    op.drop_table("tender")
    # ### end Alembic commands ###
